//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABOUTU
    {
        public int id { get; set; }
        public string aboutname { get; set; }
        public string aboutavt { get; set; }
        public string aboutcontent { get; set; }
        public string aboutimges { get; set; }
    }
}
