//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRICT
    {
        public DISTRICT()
        {
            this.PROPERTies = new HashSet<PROPERTY>();
            this.STREETs = new HashSet<STREET>();
            this.WARDs = new HashSet<WARD>();
        }
    
        public int ID { get; set; }
        public string DistrictName { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<PROPERTY> PROPERTies { get; set; }
        public virtual ICollection<STREET> STREETs { get; set; }
        public virtual ICollection<WARD> WARDs { get; set; }
    }
}
